version: '3'

services:
  psqlDb:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      POSTGRES_DB: AuthDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - auth_db_volume:/var/lib/postgresql/data

  backend:
    build:
      context: ./back-end/
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - '3333:3333'
    depends_on:
      - psqlDb
    volumes:
      - ./src:/app/src

  frontend:
    build:
      context: ./front-end/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      
volumes:
  auth_db_volume:
